######################################################################
#
# File name : uart_ram_tb.udo
# Created on: Sun Aug 02 22:34:00 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
