######################################################################
#
# File name : uart_ram_tb_wave.do
# Created on: Sun Aug 02 22:34:00 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
