######################################################################
#
# File name : uart_ram_tb_compile.do
# Created on: Mon Aug 03 08:38:04 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\STUDY\\Modelsim\\win64\\vlib modelsim_lib/work
D:\\STUDY\\Modelsim\\win64\\vlib modelsim_lib/msim

D:\\STUDY\\Modelsim\\win64\\vlib modelsim_lib/msim/dist_mem_gen_v8_0_13
D:\\STUDY\\Modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\STUDY\\Modelsim\\win64\\vmap dist_mem_gen_v8_0_13 modelsim_lib/msim/dist_mem_gen_v8_0_13
D:\\STUDY\\Modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\STUDY\\Modelsim\\win64\\vlog -64 -incr -work dist_mem_gen_v8_0_13  \
"../../../../vivado.ip_user_files/ipstatic/simulation/dist_mem_gen_v8_0.v" \

D:\\STUDY\\Modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../vivado.srcs/sources_1/ip/dmg_ram/sim/dmg_ram.v" \
"../../../../../verilog/uart_baud.v" \
"../../../../../verilog/uart_ram.v" \
"../../../../../verilog/uart_rx.v" \
"../../../../../verilog/uart_top.v" \
"../../../../../verilog/uart_tx.v" \
"../../../../../verilog/uart_ram_tb.v" \

# compile glbl module
D:\\STUDY\\Modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

