# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/STUDY/GitHubWork/Verilog-learning/09_uart_ram/vivado_fpga/vivado.srcs/sources_1/ip/dmg_ram/dmg_ram.xci
# IP: The module: 'dmg_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/STUDY/GitHubWork/Verilog-learning/09_uart_ram/vivado_fpga/vivado.srcs/sources_1/ip/dmg_ram/dmg_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmg_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/STUDY/GitHubWork/Verilog-learning/09_uart_ram/vivado_fpga/vivado.srcs/sources_1/ip/dmg_ram/dmg_ram.xci
# IP: The module: 'dmg_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/STUDY/GitHubWork/Verilog-learning/09_uart_ram/vivado_fpga/vivado.srcs/sources_1/ip/dmg_ram/dmg_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dmg_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
