@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Jul 28 21:36:05 +0800 2020
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim decode_47_tb_behav -key {Behavioral:sim_1:Functional:decode_47_tb} -tclbatch decode_47_tb.tcl -view D:/STUDY/GitHubWork/Verilog-learning/07_decode_47/decode/decode_47_tb_behav.wcfg -log simulate.log"
call xsim  decode_47_tb_behav -key {Behavioral:sim_1:Functional:decode_47_tb} -tclbatch decode_47_tb.tcl -view D:/STUDY/GitHubWork/Verilog-learning/07_decode_47/decode/decode_47_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
